/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oxFT1ErvKjM
 */
import axios from "axios"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useRouter } from "next/router"

export function Hero() {
  const router = useRouter()

  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 flex justify-center bg-blue-500">
      <div className="container flex flex-col items-center justify-center gap-4 px-4 md:px-6">
        <div className="space-y-2 text-center">
          <h1 className="text-4xl font-bold text-white tracking-tighter sm:text-5xl md:text-6xl/none">The Game of Life</h1>
          <p className="mx-auto max-w-[600px] text-white md:text-xl ">
            Enter your name and date of birth to reveal your destiny.
          </p>
        </div>
        <div className="w-full max-w-sm space-y-4">
          <form className="grid grid-cols-2 gap-2">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="dob">Date of Birth</Label>
              <Input id="dob" placeholder="Enter your name" required type="date" />
            </div>
            <Button onClick={()=>{
              router.push('/game')
            }} className="col-span-2 w-full" type="submit">
              Start Game
            </Button>
          </form>
        </div>
      </div>
    </section>
  )
}
